

//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Examen_Tarjeta.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;


public partial class Examen_TarjetaEntities : DbContext
{
    public Examen_TarjetaEntities()
        : base("name=Examen_TarjetaEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public DbSet<Tbl_Tarjeta> Tbl_Tarjeta { get; set; }


    public virtual int Delete_Tarjeta(Nullable<int> id)
    {

        var idParameter = id.HasValue ?
            new ObjectParameter("Id", id) :
            new ObjectParameter("Id", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Delete_Tarjeta", idParameter);
    }


    public virtual int Edit_Estado(Nullable<int> iD, Nullable<bool> estado)
    {

        var iDParameter = iD.HasValue ?
            new ObjectParameter("ID", iD) :
            new ObjectParameter("ID", typeof(int));


        var estadoParameter = estado.HasValue ?
            new ObjectParameter("Estado", estado) :
            new ObjectParameter("Estado", typeof(bool));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Edit_Estado", iDParameter, estadoParameter);
    }


    public virtual int Insert_Tarjetas(string numeroTarjet, Nullable<int> cVV, Nullable<System.DateTime> fecha_Exp, string banco, string fotoBanco, string emisor, string dueno)
    {

        var numeroTarjetParameter = numeroTarjet != null ?
            new ObjectParameter("NumeroTarjet", numeroTarjet) :
            new ObjectParameter("NumeroTarjet", typeof(string));


        var cVVParameter = cVV.HasValue ?
            new ObjectParameter("CVV", cVV) :
            new ObjectParameter("CVV", typeof(int));


        var fecha_ExpParameter = fecha_Exp.HasValue ?
            new ObjectParameter("Fecha_Exp", fecha_Exp) :
            new ObjectParameter("Fecha_Exp", typeof(System.DateTime));


        var bancoParameter = banco != null ?
            new ObjectParameter("Banco", banco) :
            new ObjectParameter("Banco", typeof(string));


        var fotoBancoParameter = fotoBanco != null ?
            new ObjectParameter("FotoBanco", fotoBanco) :
            new ObjectParameter("FotoBanco", typeof(string));


        var emisorParameter = emisor != null ?
            new ObjectParameter("Emisor", emisor) :
            new ObjectParameter("Emisor", typeof(string));


        var duenoParameter = dueno != null ?
            new ObjectParameter("Dueno", dueno) :
            new ObjectParameter("Dueno", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Insert_Tarjetas", numeroTarjetParameter, cVVParameter, fecha_ExpParameter, bancoParameter, fotoBancoParameter, emisorParameter, duenoParameter);
    }


    public virtual int Edit_Tarjetas(Nullable<int> iD, string numeroTarjeta, Nullable<int> cVV)
    {

        var iDParameter = iD.HasValue ?
            new ObjectParameter("ID", iD) :
            new ObjectParameter("ID", typeof(int));


        var numeroTarjetaParameter = numeroTarjeta != null ?
            new ObjectParameter("NumeroTarjeta", numeroTarjeta) :
            new ObjectParameter("NumeroTarjeta", typeof(string));


        var cVVParameter = cVV.HasValue ?
            new ObjectParameter("CVV", cVV) :
            new ObjectParameter("CVV", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Edit_Tarjetas", iDParameter, numeroTarjetaParameter, cVVParameter);
    }


    public virtual ObjectResult<Get_Tarjeta_Result> Get_Tarjeta(Nullable<int> id)
    {

        var idParameter = id.HasValue ?
            new ObjectParameter("id", id) :
            new ObjectParameter("id", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_Tarjeta_Result>("Get_Tarjeta", idParameter);
    }


    public virtual ObjectResult<Get_Tarjetas_Result> Get_Tarjetas(string param)
    {

        var paramParameter = param != null ?
            new ObjectParameter("Param", param) :
            new ObjectParameter("Param", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_Tarjetas_Result>("Get_Tarjetas", paramParameter);
    }


    public virtual ObjectResult<Get_TarjetasRespaldo_Result> Get_TarjetasRespaldo(string param)
    {

        var paramParameter = param != null ?
            new ObjectParameter("Param", param) :
            new ObjectParameter("Param", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_TarjetasRespaldo_Result>("Get_TarjetasRespaldo", paramParameter);
    }

}

}

